### ISSUE TITLE
Wrong keys in upc_keys.py3

### ISSUE THREAD

**Issue by Leseratte10** [dionbosschieter/upc_keys#1]
The Python script returns wrong keys: 

I've tested with input "1234567" and compared the Python output to the reference output at https://haxx.in/upc-wifi/ 

The Python script returned both wrong and too few results. Why is that?

In addition, the MAGIC values for 2.4 and 5 are swapped.

**Comment by dionbosschieter** [comment]
Hi,

Thank you for your interests. I found out that there are some problems with computing ssid or the hash.
I am not quite sure what it is because I was a bit busy. I'll take a look at it today and let you know what I found out and how I fixed it :).

**Comment by dionbosschieter** [comment]
Hi, 

I fixed the strange swapping of 5GHZ to 24GHZ because I mixed up the magics :/ haha.
I also added a performance improvement and fixed the computation of the passwords.
I still need to fix the bug that causes some of the serial to SSIDs to be excluded.
I will get back to you on that asap.

Thx again.

**Comment by dionbosschieter** [comment]
So I found out why it wasn't checking on al SSIDs and I fixed it.
Turns out `range(0, 9999)` does not give you a list starting with 0 ending with 9999 \O/, stupid mistake but it works now.

**Comment by Leseratte10** [comment]
Calculation works now correctly. However there is now a small displaying error: The SSID for the 5 GHz WLANs is displayed in reverse (probably because it is reversed for the calculations)

**Comment by dionbosschieter** [comment]
Yes that is correct.

You can submit a pull request fixing it if you want :-).

**Comment by Leseratte10** [comment]
Done :P

**Comment by dionbosschieter** [comment]
Merged it!
